# docker-compose.yml

services:
  frontend:
    image: node:18-alpine
    container_name: workplace-optimizer-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    ports:
      - '${FRONTEND_PORT:-3000}:3000'
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      - NEXT_PUBLIC_API_URL=http://backend:8000/api
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: node:18-alpine
    container_name: workplace-optimizer-backend-dev
    working_dir: /app
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - backend_dist:/app/dist
    ports:
      - '${BACKEND_PORT:-8000}:8000'
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - TS_NODE_CACHE=false
      - TS_NODE_TRANSPILE_ONLY=true
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: workplace-optimizer-redis-dev
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  frontend_node_modules:
    driver: local
  frontend_next:
    driver: local
  backend_node_modules:
    driver: local
  backend_dist:
    driver: local
  redis_data:
    driver: local
