import express from 'express';
import { generateTextController } from '../controllers/generationController'; // We will create this controller next

const router = express.Router();

/**
 * @swagger
 * /api/v1/generate:
 *   post:
 *     summary: Generate text using a selected AI model
 *     tags: [Generation]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - modelId
 *               - inputText
 *             properties:
 *               modelId:
 *                 type: string
 *                 description: The ID of the AI model to use.
 *                 example: "gpt-4o"
 *               inputText:
 *                 type: string
 *                 description: The text input by the user.
 *                 example: "this is a test input, pls make it better."
 *               systemPrompt:
 *                 type: string
 *                 description: (Optional) A system prompt or task description for the AI.
 *                 example: "Rewrite the following text to be more professional and concise."
 *     responses:
 *       200:
 *         description: Successfully generated text.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 generatedText:
 *                   type: string
 *                   description: The text generated by the AI model.
 *                 modelUsed:
 *                   type: string
 *                   description: The ID of the model that was used.
 *       400:
 *         description: Bad request (e.g., missing parameters, invalid modelId).
 *       500:
 *         description: Internal server error or error from AI provider.
 */
router.post('/generate', generateTextController);

export default router;
